### ISSUE TITLE
Questions for AWUDS folks

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/wateRuse#1]
1. In comparison datasets, do missing data descriptions mean different things? E.g. `Null`, `No Data`, `****`, empty cells 
2. Is there a standard structure for headers (esp when merged cells are involved)? It is difficult for R to understand merged column names. The basic tables datasets have a lot of merged column names. See my issue for the `readxl` package: https://github.com/hadley/readxl/issues/166

**Comment by twaugens-usgs** [comment]
1. See below
2. The headers change based on the compilation year, area type, and data storage option selections the user made at the time the data set was created.

AWUDS only has the ability to output data directly into Excel.
Only 1 dataset can be output at a time with the exception of the compare 2 datasets report.
A dataset contains annual values for 1 State, 1 Area Type, and 1 year.
You can not output multiple years in a report.
A value is either entered by the user or calculated by AWUDS.
A value is associated to 1 water-use category.
A category has a code and a long name, e.g. IN, Industrial.
Categories come and go with time.
A value is associated to 1 data element. 
A data element has a number, a code, and a name.
e.g. 
number: 61
code: WSWSa
Name: self-supplied surface-water withdrawals, saline, in Mgal/d
A data element is associated to 1 category.
A data element tag is the concatenation of the category code and data element code.
e.g. IN-WSWSa
Users should know what the value is by its data element tag.
The long name of the data element tag would be:
Industrial, self-supplied surface-water withdrawals, saline, in Mgal/d
A dataset has a fixed set of data elements.
The fixed set of data elements change over time.
A dataset has a fixed set of areas: states, counties, huc4, huc8, aquifer, or countyaquifer areas.
Areas come and go with time, the areas are tagged with a year range in which they exist.
AWUDS datasets are based on calendar years.
A dataset has a fixed set of areas based on the calendar year. 
AWUDS has a defualt file naming convention.
The user can override the default file name and name the files anything they want.
The user has a few choices of what data elements will be entered that is determined when the dataset is created.
Once the set of data elements have been chosen and the dataset created the set of data elements cannot be changed.

Export-Wisconsin-County-2005.xlsx
Export report for Wisconsin for Counties in 2005.
The export report only contains values the user entered. 
The export report does not include calculations.
The set of worksheets and worksheet names are not static, they change based on State, Area Type, and Year.
Each worksheet is labeled with the category code for those categories that existed for county data in 2005 for the data element choices the user made when the dataset was created.
The first column is always called Area.
The first column has the area code.
The first column cell comment has the area name.
Only areas that existed in 2005 are listed.
Only areas that the user choose to output are listed.
Only category tabs the user choose to output are listed.
Line 2 contains the Dataset Name.
The State, Area Type, Year, and Dataset Name make the dataset unique.
Blank cells means no data was entered, it does not mean zero.
If a value was zero, then the user would have entered zero.

Basic-Tables-by-Category-Wisconsin-County-2005.xlsx
Basic-Tables-by-Category (BTBC) report for Wisconsin for Counties in 2005.
BTBC is different from export in that:
The BTBC report contains both entered data and calculations. 
The user can output either the area code, area name, or both as either
the first or first and second columns.
Blank cells means no data was entered, it does not mean zero.
If a blank cell is included in a calculation then the result is a blank cell.
The report includes a total line.
Because of the blank cell rule, a total can be blank.
***\* means a divide by zero occurred.
The BTBC is the only report having grand total summary tabs.
TS, total surface water
TG, total groundwater
TO, toals
TW, total SW and GW

NOTE the file I sent had an error in the name State should have been County:
Compare-Data-for-2-Datasets-Wisconsin-County-2005-vs-2010.xlsx
Compare-Data-for-2-Datasets report for Wisconsin for Counties in 2005 compared to 2010.
Compare-Data-for-2-Datasets is different from BTBC in that:
Datasets being compared can have a different set of data elements.
No DataElement means the data element does not exist in that dataset.
No Calulation means the calculation cannot be preformed in that dataset.
Null means the value is null, no data was entered, the value is not zero, its nothing.
***\* means a divide by zero occurred.
No Data means a calculation could not be preformed because of null values.

**Comment by twaugens-usgs** [comment]
AWUDS does have a dump program that dumps data as described here:

http://nwis.usgs.gov/awuds/dump/instructions_awuds_dump.html

The files have standard headers that do not change, and all possible data elements
and calculations are included in the dump. If a data element or calculation does not exist for a dataset then those columns are null.

Included in the dump directory is a sub-directory of MS Access Databases. The databases can be used to link to the tab delimited dump files in read-only mode. A script in the database can be used to reset the links.

The down side ... the dump includes non-approved data. 
AWUDS access is done with Active Directory and is controlled by the AWUDS client.
http://nwis.usgs.gov/IT/awuds/awudsgroups.htm
If a user is in a group then they have WRITE access and can see non-approved data
for the listed state. Users in group IGSGRESTONVA-M HQ W NWULT can also see everything.

All other users have READ access and should only see approved data.

The dump file by-passes security.
If the dump files are used, then somehow the data will need to be filtered to avoid showing people non-approved data when they should not have access to view it.

e.g of a header:
head ahuc8_pc.txt
STUDY   DATASETNAME     BESTAVAILABLE   USSTATEALPHACODE        STATECODE       HUCCODE USSTATEHUCCODE  HUCNAME YEAR    PC-WGWFr        PC-WGWSa        PC-WGWTo        PC-WSWFr        PC-WSWSa        PC-WSWTo        PC-WFrTo        PC-WSaTo        PC-WTotl        PC-PSDel        PC-WDelv        PC-CUsFr        PC-CUsSa        PC-CUTot        PC-Power        PC-RecWW        PC-Facil

**Comment by dblodgett-usgs** [comment]
In conversation with water use information leadership, we determined that regional staff and people who would otherwise have access to the dump file, should be able to read it in and work with it in this tool. Users who should not have access to the dump file or are working on data that has not made it to the national dump file yet will need to make multiple exports from AWUDS according to their local privileges using the excel format.

**Comment by twaugens-usgs** [comment]
Another option is the Multi State Dataset (MSD) output. Users have the ability to identify a set of datasets to output in the same report. There can be a set of 1 datasets. For some QA work users will likely want to see neighboring States datasets. 

The advantage of using a MSD is that the MSD Export program uses the same views as the dump program. And the MSD export includes both entered data elements and calculations, like the dump output. The header line is much easier to read than the Basic Tables by Category report, no merged headers. The rules for what the user sees remains intact. If you have READ access to a State you only see approved data for that State.

The down side, the user has to create the MSD dataset. However, that is a one time task.

This is an example, it was included in the sample output:

Export-MyRegion-UserCreated-msd-2010.xlsx

**Comment by dblodgett-usgs** [comment]
From what I remember, our decision was to use the national dump file for regional and national review activities because the reviewers felt like creating the MSD dataset would be too onerous. But it's good to have the full breadth of possibilities on the record. Thanks @twaugens-usgs!
