### ISSUE TITLE
Package Updates

### ISSUE THREAD

**Issue by grrmartin-USGS** [USGS-R/wateRuse#139]
When I initially tried to install the Animation package, R said that it was not available for the version I am using, 3.2.5. Since then, it has become available. However, the saveHTML package used with Animation is not available for the current R.  Is it the 'maintainer' that needs to update their packages to new versions of R?  What will that entail for wateRuse updates?

**Comment by ldecicco-USGS** [comment]
Well, the `wateRuse` package doesn't currently use the `animation` package...so that's not currently a problem. 

I'd vote that people use browser tools to save an HTML page (both Chrome and Firefox do it well). The `animation` package is nice, but pretty heavy if that's all you need.

The CRAN mirror you are using is what determines if a package's binaries are up-to-date. That's why I strongly recommend:
https://cloud.r-project.org

**Comment by dblodgett-usgs** [comment]
Taken care of by GRAN for wateRUSe.
