### ISSUE TITLE
Rank data elements

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/wateRuse#6]
We want to be able to see areas (county/HUC/aquifer/state) values ranked for data elements that we can pick from a picklist, for all available years.  

QAQC would include pairing two ranked lists for the same element between 2 or more years to see how areas have shifted between years. For example, total public supply by county between 2010 and 2015.

**Comment by ldecicco-USGS** [comment]
```
df <- data.frame(
  county = c("A","B","C"),
  pop_2010 = c(2,3,4),
  pop_2015 = c(4,3,2),
  stringsAsFactors = FALSE
)

library(dplyr)

sortDF <- arrange(df, desc(pop_2015))
```

**Comment by ldecicco-USGS** [comment]
Need a lookup table to convert element to category (sheet tab names)

**Comment by ldecicco-USGS** [comment]
After discussion, we want the argument to just be the path to the files, the file names must use the default AWUDS output.

So that means, we need:
- [ ] The file names in the package needs to be standard
- [ ] We need a sample dump file

**Comment by jshourds-usgs** [comment]
Default output filenames from AWUDS are:
Export_2010, New Jersey_County.xlsx
Export_2016, New Jersey_HUC - 8.xlsx

**Comment by dblodgett-usgs** [comment]
@ldecicco-USGS This should also be done based on work completed in #63 ?

**Comment by dblodgett-usgs** [comment]
Playing around with this, if multiple counties are passed in as the area column, it works as expected. However, if you pass in a state as the area column, it doesn't know what to do since it needs a secondary area column or some other pre-filter. I think we need to implement a pre-filter on USSTATEALPHACODE that will subset a national dump file to a particular (or list of) states. Then offer the list of counties as the 'Choose Areas' is done now.
